<?php
# Only show partial if data is set
if(array_key_exists('contact_campaign',$this->aPartialData)) {
    # add address form fields
    $aHistories = $this->aPartialData['contact_campaign']['oHistories'];
    $aFields = $this->aPartialData['contact_campaign']['aFormFields'];

    if(count($aHistories) == 0) { ?>
        <div class="alert alert-info px-2 py-2">
            <?=$this->translate('No Campaign yet')?>
        </div>
    <?php } else { ?>
        <ul class="list-group">
        <?php
        foreach($aHistories as $oHist) { ?>
            <li class="list-group-item">
                <div class="row">
                    <?= $this->partial('partial/viewformfields', ['sFormName' => 'contactcampaign-single', 'sTab' => 'campaign-base', 'oItem' => $oHist, 'aFormFieldsByTab' => $aFields]); ?>
                </div>
            </li>
        <?php
        }
        ?>
        </ul>
    <?php
    }
} else { ?>
    <div class="alert alert-danger px-2 py-2">
        <?= $this->translate('Could not loadcontact campaign') ?>
    </div>
    <?php
}

